run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck      # Unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Unused constants, variables, functions
    
    # Additional recommended linters
    - gofmt         # Checks code formatting
    - goimports     # Check import statements
    - misspell      # Finds commonly misspelled words
    - revive        # Drop-in replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - goconst       # Finds repeated strings that could be constants
    - gosec         # Security checks
    - prealloc      # Finds slice declarations that could be preallocated
    - predeclared   # Find code that shadows predeclared identifiers
    - whitespace    # Detects unnecessary whitespace
    - stylecheck    # Replacement for golint with extra checks

  disable:
    - typecheck     # Can conflict with go modules
    - godot         # Too strict for comment formatting
    - gocognit      # Cognitive complexity - too strict for tests

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow      # Too many false positives

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  unused:
    check-exported: false

  unparam:
    check-exported: false

  gocognit:
    min-complexity: 20

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

  gosec:
    excludes:
      - G204  # Audit use of command execution - we use it for valid reasons

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
        - goconst
        - govet  # field alignment is not critical in tests
    
    # Exclude known issues
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    
    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
